### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by valenting** [rosedu/opendata.rosedu.org#2]
A license needs to be chosen for this repo.
All contributors need to agree with the chosen license.
A list of contributors is enclosed below:
- [x] Alex Morega @mgax

(This message was generated automatically.)

**Comment by lauuuuuura** [comment]
MIT License?

**Comment by mgax** [comment]
Not sure, it's not code but content, maybe some CC license is more appropriate? I'd go with CC-BY.

**Comment by palcu** [comment]
O să adaug codul făcut la școala de vară pe acest repo. Am vorbit cu studenții și am stabilit că vom folosi licența liberă MIT.
